# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d50f84f549c0898bc103af3565e5303e282ea1372278e7241a20468397031fd13e0da030b3f359e676f9222051e114cb04146a5487da6d3855a6eae8ac25d3c

test:
  secret_key_base: 76349df4d6c2791ec5269464fe81c5372198a75298244467455ddc015feff6866dfd7bc259892481c9211579889c7a30ddea259ab0c91ad8a24a46be02bc8469

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
